AMCE/urls.py
from django.contrib import admin
from django.urls import include, path
from AMCE.forms import CustomAuthForm
from django.contrib.auth import views as auth_views

#se agrega para heroku
#from django.conf import settings 
#from django.conf.urls.static import static

# Views
import AMCE.views as views

app_name = "AMCE"
urlpatterns = [
#URLS CRECIÓN DE TIPOS DE USUARIOS
path('estudiante/vistaEstudiante/', views.vistaAlumno, name = 'vistaAlumno'),
path('profesor/vistaProfesor/', views.vistaProfesor, name = 'vistaProfesor'),
# URLS COMPARTIDAS
path('', views.index, name = 'index'),
path('registro/', views.signup, name = 'signup'),
path('registro/estudiante/', views.EstSignup.as_view(), name='EstSignup'),
path('registro/profesor/', views.ProfSignup.as_view(), name='ProfSignup'),
# URLS ESTUDIANTE
path('estudiante/MisGrupos/', views.EstMisGrupos, name = 'EstMisGrupos'),
path('estudiante/InscribirGrupo/', views.EstInscribirGrupo, name = 'EstInscribirGrupo'),
path('estudiante/Grupo/<str:id_grupo>/', views.EstPaginaGrupo, name = 'EstPaginaGrupo'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/actividad/aviso', views.AvisoNoContinuar, name = 'AvisoNoContinuar'),

path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/', views.AnalisisPreguntaInicial, name = 'AnalisisPreguntaInicial'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntaInicial/', views.postPreguntaInicial, name = 'PreguntaInicial'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntaInicial/actividad/aviso', views.AvisoNoContinuarAnalisis, name = 'AvisoNoContinuarAnalisis'), 
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntaInicial/FeedPreguntaInicial/', views.feedPIHecha, name = 'feedPIHecha'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntaInicial/DefiniciónPreguntaInicial/', views.defPreguntaInicial, name = 'defPreguntaInicial'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntasSecundarias/', views.PreguntasSecundarias, name = 'PreguntasSecundarias'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntasSecundarias/actividad/aviso', views.PSAvisoNoContinuar, name = 'PSAvisoNoContinuar'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntasSecundarias/evaluación', views.EvaluacionPS, name = 'EvaluacionPS'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntasSecundarias/evaluación/evaluacionsecundarias', views.EvaluacionPreSec, name = 'EvaluacionPreSec'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntasSecundarias/evaluación/aviso', views.AvisoNoContinuarEvaPS, name = 'AvisoNoContinuarEvaPS'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntasSecundarias/evaluación/actividad/plandeevaluación', views.PlanDeInvestigacion, name = 'PlanDeInvestigacion'),


# URLS ESTUDIANTE Paso 2
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/fuentes', views.seleccionaFuentes, name = "seleccionFuentes"),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/<str:definirFuente>/nueva-fuente', views.FuenteCreateView.as_view(), name = 'CrearFuenteView'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/editar-fuente/<pk>', views.FuenteUpdateView.as_view(), name = 'FuenteUpdateView'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/eliminar-fuente/<pk>', views.FuenteDeleteView.as_view(), name = 'FuenteDeleteView'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/instrucciones-evaluar-fuentes', views.instuccionesNuevaFuente, name = 'instuccionesNuevaFuente'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/EvaluarFuentes', views.evaluarFuentes, name = "evaluarFuentes"),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/EvaluarFuentes/aviso', views.AvisoNoContinuarEvaFuentes, name = "AvisoNoContinuarEvaFuentes"),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/EvaluarFuentes/aviso2', views.AvisoNoContinuarEvaFuentes2, name = "AvisoNoContinuarEvaFuentes2"),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/EvaluarFuentes/PlanDeInvestigaciónPaso2', views.EvaluarFuentesPlanInvestigación, name = "EvaluarFuentesPlanInvestigación"),

# URLS PROFESOR
path('profesor/MisGrupos/', views.ProfMisGrupos, name = 'ProfMisGrupos'),
path('profesor/CrearGrupo/', views.ProfCrearGrupo, name = 'ProfCrearGrupo'),
path('profesor/Grupo/<str:id_grupo>/', views.ProfPaginaGrupo, name = 'ProfPaginaGrupo'),
path('profesor/Grupo/<str:id_grupo>/CrearEquipo/', views.ProfCrearEquipo, name = 'ProfCrearEquipo'),
path('profesor/Grupo/<str:id_grupo>/Equipo/<int:id_equipo>/', views.ProfPaginaEquipo, name = 'ProfPaginaEquipo'),
path('profesor/Grupo/<str:id_grupo>/AsignarTema/', views.ProfAsignarTemaGrupo, name = 'ProfAsignarTemaGrupo'),
path('profesor/Grupo/<str:id_grupo>/Tema/<int:id_tema>/', views.ProfTemaAsignado, name = 'ProfTemaAsignado'),
path('profesor/Grupo/<str:id_grupo>/Tema/<int:id_tema>/ProgresoGrupo', views.ProfProgresoGrupo, name = 'ProfProgresoGrupo'),
path('profesor/Grupo/<str:id_grupo>/Tema/<int:id_tema>/Equipo/<int:id_equipo>', views.ProfProgresoEquipo, name = 'ProfProgresoEquipo'),
path('profesor/Grupo/<str:id_grupo>/Tema/<int:id_tema>/Equipo/<int:id_equipo>/<int:paso>', views.ProfRetro, name = 'ProfRetro'),
path('profesor/MisTemas/', views.ProfMisTemas, name = 'ProfMisTemas'),
path('profesor/CrearTema/', views.ProfCrearTema, name = 'ProfCrearTema')
]

TesisImp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
#Importamos las vistas de la aplicación django AMCE
from AMCE import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("AMCE.urls")),
    path('accounts/', include('django.contrib.auth.urls'))
]

urlpatterns += staticfiles_urlpatterns()

AMCE/views/compartidas.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from ..forms import *
from django.contrib.auth import authenticate, login
from django.template import RequestContext
from django.contrib.auth.models import User
from ..models import *
from django.urls import reverse

def index(request):
	if request.method == 'POST':
		form = CustomAuthForm(data=request.POST)
		if form.is_valid():
			user = authenticate(username=form.cleaned_data["username"], password=form.cleaned_data["password"])
			print(user)
			if user is not None:
				login(request,user)
				if user.es_estudiante:
					return redirect('AMCE:vistaAlumno')
				elif user.es_profesor:
					return redirect('AMCE:ProfMisGrupos')
	else:
		form = CustomAuthForm()
	return render(request,'index.html',{"form": form})

def signup(request):
	return render(request,"registration/signup.html")

	

AMCE/views/estudiante.py
from pickle import FALSE
from pyexpat import ParserCreate
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from ..forms import *
from django.contrib.auth import authenticate, login
from django.template import RequestContext
from django.contrib.auth.models import User
from django.views.generic import (CreateView, UpdateView, DeleteView)
from django.views.generic.edit import FormView
from ..models import *
from ..decorators import student_required
from django.urls import reverse
#se importa para aumentar el contador de votos en feed
from django.db.models import F
from django.conf import settings
from django.core.mail import send_mail
import datetime
#Para obtener el max de votos en una pregunta inicial
from django.db.models import Max
#para la bíusqueda de fuentes del paso 2
import requests
#redirect
from django.urls import reverse_lazy
from js.momentjs import moment
from django.utils.decorators import method_decorator
#para harcordear el json
import json


class EstSignup(CreateView):
	model = User
	form_class = EstSignupForm
	template_name = 'registration/signup_form.html'
	
	def get_context_data(self, **kwargs):
		kwargs['user_type'] = 'Estudiante'
		return super().get_context_data(**kwargs)

	def form_valid(self, form):
		user = form.save()
		login(self.request, user)
		return redirect('AMCE:EstMisGrupos')
		

@student_required
def vistaAlumno(request):
	current_user = get_object_or_404(User, pk=request.user.pk)
	#Comento esta linea porque me daba error sin saber el por qué
	#grupos_inscritos = Estudiante.objects.filter(user_estudiante=current_user.id).values_list('grupos_inscritos', flat=True)

	#Se agregan estas lineas con el fin de sustituir la linea de arriba 
	estudiante = Estudiante.objects.get(user_estudiante=current_user.id)
	#Consultamos todos grupos a los cual el usuario estudiante está inscrito y los mostramos
	grupos_inscritos = estudiante.grupos_inscritos.all()

	return render(request,"estudiante/MisGrupos.html", {'grupos_inscritos':grupos_inscritos})

@student_required
@login_required
def EstInscribirGrupo(request):
	'''
	Función para que un usuario alumno pueda inscribir una matería dado un código de clase
	por parte del profesor 
	'''
	current_user = get_object_or_404(User, pk=request.user.pk)
	grupos_inscritos = Estudiante.objects.filter(user_estudiante=request.user.pk)
	
	if request.method == 'POST':
		form = FormInscribirGrupo(request.POST)
		if form.is_valid():
			repetido = Estudiante.objects.filter(user_estudiante=current_user.id, grupos_inscritos=form.cleaned_data['codigo'])
			codigo = form.cleaned_data['codigo']
			try:
				if repetido.exists():
					messages.success(request, 'Ya estás inscrito en el grupo con código ' + codigo)
					return redirect(to="AMCE:EstMisGrupos")
				else:
					grupo = Grupo.objects.get(id_grupo=codigo)
					grupo_a_inscribir= Estudiante(user_estudiante_id=current_user.id)
					grupo_a_inscribir.grupos_inscritos.add(grupo.id_grupo)
					grupo_a_inscribir.save()
					messages.success(request, 'Grupo inscrito')
					return redirect(to="AMCE:EstMisGrupos")
			except Grupo.DoesNotExist:
				messages.error(request, 'El código de grupo que ingresaste no es válido')
				return redirect(to="AMCE:EstMisGrupos")
	else:
		form = FormInscribirGrupo()

	return render(request, 'estudiante/InscribirGrupo.html', {'form': form})

@student_required
@login_required
def EstMisGrupos(request):
	'''
	Función la cual muestra al usuario alumno los grupos a los cuales está inscrito  
	'''
	current_user = get_object_or_404(User, pk=request.user.pk)
	#Obtenemos el objeto estudiante actual
	estudiante = Estudiante.objects.get(user_estudiante=current_user.id)
	#Consultamos todos grupos a los cual el usuario estudiante está inscrito y los mostramos
	grupos_inscritos = estudiante.grupos_inscritos.all()

	return render(request,"estudiante/MisGrupos.html",{'grupos_inscritos':grupos_inscritos})

@student_required
@login_required
def EstPaginaGrupo(request, id_grupo):
	'''
	Función la cual muestra los temas asignados al equipo del usuario.
	Un usuario debe de tener un equipo pero este puede ser diferente para cada tema, lo que se hace es que 
	se haga una búsqueda que llegue hasta la tabla Asignar, la cual muestra que equipos (id) tienen el tema (id)
	Args:
		id_grupo (char): código de la materia 
	'''
	#Se verifica que el usuario tenga equipo
	try:
		current_user = get_object_or_404(User, pk=request.user.pk)
		#Se obtiene el objeto Equipo de nuestro actual estudiante
		print("current_user", current_user)
		equipo = Equipo.objects.get(estudiantes=current_user.id, grupo_equipo=id_grupo)
		print("equipo", equipo)
		#Consultamos los temas asigandos que tiene el equipo del usuario y los filtramos por materia 
		temas_asignados = equipo.temas_asignados.filter()
		print("temas_asignados", temas_asignados[0].id_tema)
		#Consultamos e identificamos el grupo actual para mostrar los datos de grupo y materia en el header 
		grupo = Grupo.objects.filter(id_grupo = id_grupo)
	#De no tener equipo se le notifica que aún no tiene equipo
	except Equipo.DoesNotExist:
		messages.error(request, 'Aún no tienes equipo, espera a que tu profesor te asigne uno.')
		return redirect('AMCE:EstMisGrupos')
	

	return render(request, 'estudiante/PaginaGrupo.html', {'grupo':grupo.first(),'id_grupo':id_grupo ,'temas_asignados':temas_asignados})	

@student_required
@login_required
def AvisoNoContinuar(request, id_tema, id_grupo):
	'''
	Funcion para mostrar el aviso de que el equipo aún no acaba esta parte
	'''
	current_user = get_object_or_404(User, pk=request.user.pk)
	equipo = Equipo.objects.get(estudiantes=current_user.id, grupo_equipo=id_grupo).id_equipo
	#obtengo todos los integrantes del equipo con ese id_equipo
	integrantesEquipo = Equipo.objects.filter(id_equipo=equipo).values_list('estudiantes', flat=True)
	#Se consulta el equipo actual del usuario para pasarselo como parámetro en defProbPreguntaQuery
	equipo = Equipo.objects.get(estudiantes=current_user.id, grupo_equipo=id_grupo)
	#Se obtiene el problema asignado a un equipo, esto para poder obtener el parámetro definirProb_pregunta_id
	defProbPreguntaQuery = DefinirProblema.objects.get(equipo_definirProb_id = equipo.id_equipo, tema_definirProb_id = id_tema)
	temaNombre = Tema.objects.get(id_tema=id_tema).nombre_tema

	#Por cada integrante del equipo se va a buscar su participación de la PI
	for i in integrantesEquipo:
		#Si se encuentra la participación de un usuario no pasa nada
		try:
			obj = Pregunta.objects.get(id_pregunta__estudiante_part=i, definirProb_pregunta_id=defProbPreguntaQuery, tipo_pregunta=1)
		#Si no encuentra la participación de un usuario entonces manda correo a ese usuario quién no tiene la participación
		except Pregunta.DoesNotExist:
			#Obtenemos el id para posteriormente usar el nombre del usuario en el cuerpo del mensaje
			obj2 = User.objects.get(id=i)
			send_mail(
    		'Aviso, Faltas tu!',
    		f'Hola {obj2.first_name}, tu equipo ya realizó la actividad de formular la pregunta inicial del tema {temaNombre}, faltas tu! Entra a Búsqueda Colaborativa y continua con tu proceso de investigación.',
    		settings.EMAIL_HOST_USER,
    		[obj2.email],
    		fail_silently=False,
			)
	
	return render(request, 'estudiante/AvisoNoContinuar.html', {'id_tema':id_tema, 'id_grupo':id_grupo})

@student_required
@login_required
def postPreguntaInicial(request, id_tema ,id_grupo):
	'''
	Función la cual habilita que un usuario pueda ingresar una función principal mediante un form.

	Args:
		tema (string): El tema asignado de la pregunta inicial

		codigo (string): codigo de la materia 
	
	'''
	#Consulta para obtener el tema de la actividad asignada y mostrarla en el template, así como usarla en defProbPreguntaQuery
	temaPreguntaInicial = Tema.objects.get(id_tema=id_tema)
	current_user = get_object_or_404(User, pk=request.user.pk)
	#Se consulta el equipo actual del usuario para pasarselo como parámetro en defProbPreguntaQuery
	equipo = Equipo.objects.get(estudiantes=current_user.id, grupo_equipo=id_grupo)
	#Se obtiene el problema asignado a un equipo, esto para poder obtener el parámetro definirProb_pregunta_id
	defProbPreguntaQuery = DefinirProblema.objects.get(equipo_definirProb_id = equipo.id_equipo, tema_definirProb_id = temaPreguntaInicial.id_tema)
	#Obtenemos todas las participaciones del equipo de nuestro actual usuario (AGREGAR CÓMO PARÁMETRO 1 COMO PREGUNTA INICIAL)
	numTotalPartici = Pregunta.objects.filter(definirProb_pregunta=defProbPreguntaQuery.id_definirProb, tipo_pregunta=1)
	#Obtenemos los integrantes del  equipo (ARREGLAR ESTO)
	integrantesEquipo = Equipo.objects.filter(id_equipo=equipo.id_equipo).values_list('estudiantes', flat=True)

	#Se obtienen los ids del usuario actual 
	idsUsuarioParticipacion = ParticipacionEst.objects.filter(estudiante_part=current_user.id).values_list('id_actividad', flat=True)
	#Se obtienen los id's de id_pregunta del numTotalPartici que asocia al equipo del actual estudiante y el del tema asignado
	idsUsuarioPregunta = numTotalPartici.values_list('id_pregunta', flat=True)
	#Verificamos para ver en qué paso se encuentra el equipo y redireccionarlo a la función correspondiente
	if defProbPreguntaQuery.paso == 1:
		#Se pregunta si el numero total de particiapciones con id_definirProb del equipo es igual al número de integrantes
		if numTotalPartici.count() == integrantesEquipo.count():
			#Si el numero de integrantes coincide con el número de participaciones entonces pasamos al siguente paso
			return redirect('AMCE:AnalisisPreguntaInicial',id_grupo=id_grupo, id_tema=id_tema)
			#Si no lo mandamos al modal de aviso 
		else:
			#Verificamos si hay una intersección entre los ids de participaciones del usuario con los ids de las preguntas asociadas a un id de DefinirPregunta
			if bool(set(idsUsuarioParticipacion)&set(idsUsuarioPregunta)):

AMCE/templates/estudiante/2EvaluacionPreguntasSecundarias.html
{% extends "estudiante/base_mainpage.html" %}

{% load static %}

{% block extra-css %}

<style>
    .btn-secondary,.btn-primary:hover, .btn-primary:active, .btn-primary:visited {
    background-color: #6FCFA1 !important;
}

.btn-secondary.active, .btn-group, .btn-group-toggle {
    background-color: #458365 !important;
}


</style>

<style>
  @import url('https://fonts.googleapis.com/css2?family=Capriola&display=swap');
  </style>

{% endblock %}

{% block title %}
   Evaluación Preguntas Secundarias
{% endblock %}

{% block header_ctxt %}
<div class="nav-bar-title navbar-brand"> Evaluación <br> preguntas secundarias</div>
<a class=""></a>
{% endblock %}


{% block inner_content %}
<h3> <p style="font-family: 'Capriola'; font-size: 20px;"> Tema: {{ temaNombre }} </p></h3> 
<h3> <p style="font-family: 'Capriola'; font-size: 20px;"> Pregunta Inicial: {{ pregunta.id_pregunta.contenido }}  </p></h3> 
<br>
<center> <h4> Evalua las preguntas secundarias de tu equipo </h4> </center>
<br>
<br>
      <form method="post">
      {% csrf_token %}
        <div class="w3-container">
            {% for i in preguntasSec %}
                <div >
                <header >
                    <br>
                    <table style="width:100%">
                        <h4>{{ i.id_pregunta.contenido }}</h4>  
                        <div class="btn-group btn-group-toggle" data-toggle="buttons">
                            <label class="btn btn-secondary active" >
                              <input type="radio" name="options{{forloop.counter}}" id="megusta" value="3" autocomplete="off" required> Me gusta
                            </label>
                            <label class="btn btn-secondary" >
                              <input type="radio" name="options{{forloop.counter}}" id="noleentiendo" value="-1"  autocomplete="off" required> No le entiendo
                            </label>
                            <label class="btn btn-secondary" >
                              <input type="radio" name="options{{forloop.counter}}" id="nomegusta" value="-2"  autocomplete="off" required> No me gusta
                            </label>
                          </div>
                      </table>
                    <br>
                    <br>
                    
                </header>
                <br>
                </div>
            {% endfor %}


        </div>
       
        <button type="submit" style="color: white; background-color: #6FCFA1;
        border: 0px; margin-left: 40%;">Continuar al siguiente paso</button>
  </form>



<br>
<br>

{% endblock %}

{% block scripts %}

    <!-- Core theme JS-->
    <script src="{%static 'js/MG1.js' %}"></script>
    <!-- JS para modal del ingresar código de clase-->
    <script src="{%static 'js/modal.js' %}"></script>
{% endblock %}

{% block footer %}
<footer style=" margin-left: 0px;">
    <p style="position: relative; width:100%; left: 0px; bottom: 0; width: 100%;  text-align: center; color: black;">&copy; ICAT | UNAM</p>
  </footer>
{% endblock %}

AMCE/templates/estudiante/AnalisisAviso.html
{% extends "profesor/base_formpage.html" %}

{% load static %}

{% block title %}
    Aviso 
{% endblock %}

{% block header_ctxt %}
<a class="nav-bar-btn"  href="{% url 'AMCE:EstMisGrupos' %}" id="inscribir_grupo"> <img src="{% static 'assets/images/bt_grupos.png'%}"></a>
{% endblock %}

{% block navbar %}
<a class="navbar-brand" href="{% url 'AMCE:EstMisGrupos' %}"> <i  style="color: white; width: 20%; height: 20%;" class="bi bi-stopwatch"></i> </a>
    
{% endblock %}

{% block content %}


<br>
<br>
<center>
        <h5 class="h5" >Aviso</h5>
        <br>
        <p>Tu equipo aún no termina de análizar la pregunta inicial que les parezca mejor para continuar con la investigación, regresa más tarde. </p> 
    <br>
    <br>
     <a name="profesor" class="btn btn-primary" class="close" href="{% url 'AMCE:EstMisGrupos' %}" style=" background-color: #6FCFA1;
    border: 0px; padding: 5px 15px;">Entendido</a> </center>

{% endblock content %}

 
{% block scripts %}
<script>
    $(document).ready(function(){$("#myModal").appendTo("body").modal('show');});
    $("#myModal").css("z-index", "1500");
    
</script>
{% endblock %}

AMCE/templates/estudiante/EvFuentesAvisoNoContinuar2.html
{% extends "profesor/base_formpage.html" %}

{% load static %}

{% block title %}
    Aviso 
{% endblock %}

{% block header_ctxt %}
<a class="nav-bar-btn"  href="{% url 'AMCE:EstMisGrupos' %}" id="inscribir_grupo"> <img src="{% static 'assets/images/bt_grupos.png'%}"></a>
{% endblock %}

{% block navbar %}
<a class="navbar-brand" href="{% url 'AMCE:EstMisGrupos' %}"> <i  style="color: white; width: 20%; height: 20%;" class="bi bi-stopwatch"></i> </a>
    
{% endblock %}

{% block content %}

<br>
<br>
<center>
        <h5 class="h5" >Aviso</h5>
        <br>
        <p>Tu equipo aún no termina de evaluar las fuentes del equipo, regresa más tarde. </p>
    <br>
    <br>
     <a name="profesor" class="btn btn-primary" class="close" href="{% url 'AMCE:EstMisGrupos' %}" style=" background-color: #6FCFA1;
    border: 0px; padding: 5px 15px;">Entendido</a> </center>

{% endblock content %}

 
{% block scripts %}
<script>
    $(document).ready(function(){$("#myModal").appendTo("body").modal('show');});
    $("#myModal").css("z-index", "1500");
    
</script>
{% endblock %}

AMCE/templates/estudiante/EvPsAvisoNoContinuar.html
{% extends "profesor/base_formpage.html" %}

{% load static %}

{% block title %}
    Aviso 
{% endblock %}

{% block header_ctxt %}
<a class="nav-bar-btn"  href="{% url 'AMCE:EstMisGrupos' %}" id="inscribir_grupo"> <img src="{% static 'assets/images/bt_grupos.png'%}"></a>
{% endblock %}

{% block navbar %}
<a class="navbar-brand" href="{% url 'AMCE:EstMisGrupos' %}"> <i  style="color: white; width: 20%; height: 20%;" class="bi bi-stopwatch"></i> </a>
    
{% endblock %}

{% block content %}

<br>
<br>
<center>
        <h5 class="h5" >Aviso</h5>
        <br>
        <p>Tu equipo aún no termina de evaluar las preguntas secundarias, regresa más tarde. </p>
    <br>
    <br>
     <a name="profesor" class="btn btn-primary" class="close" href="{% url 'AMCE:EstMisGrupos' %}" style=" background-color: #6FCFA1;
    border: 0px; padding: 5px 15px;">Entendido</a> </center>

{% endblock content %}

 
{% block scripts %}
<script>
    $(document).ready(function(){$("#myModal").appendTo("body").modal('show');});
    $("#myModal").css("z-index", "1500");
    
</script>
{% endblock %}

AMCE/templates/estudiante/InstruccionesEvaluarFuentes.html
{% extends "estudiante/base_mainpage.html" %}

{% load static %}
   


{% block extra-css %}
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Capriola&display=swap%27');
    </style>

    
{% endblock %}

{% block title %}
    Seleccion de Fuentes
{% endblock %}

{% block header_ctxt %}
    <div class="nav-bar-title navbar-brand"> Busqueda de fuentes</div>
    <a class=""></a>
{% endblock %}

{% block inner_content %}

<center><h4>¡Enhorabuena!</h4> </center>
<br>
<br>
<h6>
    Ahora toca evaluar las fuentes seleccionadas por tu equipo <br>
    <br>
<br>
Para evaluar una fuente proveniente de internet, debes de prestar atención en tres criterios básicos:
<ul>
    <li>
        Referencias generales, propiedades y propósitos del sitio web que publica el contenido de la fuente
    </li>
    <li>
        Datos sobre el(los) autor(es) de los contenidos
    </li>
    <li>
        Caracteristicas de la información que ofrece la fuente y su nivel de confiabilidad y pertinencia para la investigación
    </li>
</ul>
</h6>
<br>
<br>
<br>
<br>

<center> <a name="profesor" class="btn btn-primary" class="close" href="{% url 'AMCE:evaluarFuentes'  id_grupo=id_grupo id_tema=id_tema %}" style=" background-color: #6FCFA1;
    border: 0px; padding: 5px 15px;" id="submit-form">Continuar al siguente paso</a></center>


{% endblock %}



{% block footer %}
<footer style=" margin-left: 0px;">
    <p style="font-family: 'Capriola'; position: absolute; width:100%; left: 0px; bottom: 0; width: 100%;  text-align: center; color: black;">&copy; ICAT | UNAM</p>
  </footer>
{% endblock %}


{% block scripts %}


{% endblock %}